### ISSUE TITLE
[milestone: 0.0.1] Minimal working product

### ISSUE THREAD

**Issue by heysokam** [OpenQuake3/defrag#1]
> Note: Backport from the original markdown todo list

### Works in default q3a
- [x] Surface flags (uses shader properties)
- [x] Vq3 movement (`pmove_fixed 1`)
- [x] Vq3 Teleports
- [x] vq3 Hurt Trigger
- [x] target score

### Changes
- [x] Initial setup & compilation (manual)
- [x] Map loading
- [x] Changes to the code actually affect gameplay through `.qvm` files

### Patchnotes
```md
# 0.0.1
new : Basic cpm strafing (Correct accel, aircontrol and A/D strafing)  
new : Instant respawn:  
... : Respawn minimum delay changed from 1700 to 0 on player_die()
... : g_forcerespawn now means miliseconds, instead of seconds  
... : g_forcerespawn default value changed to 1. Previous behavior is now `g_forcerespawn 20000`  
chg : Powerups no longer drop on player_die()  (sk->wrn : date/version might be wrong)
chg : Score is now set to 0 on player_die()
... : New function SetScore() on g_combat.c. Modified version of AddScore()
new : Gamemode "run" (basic). Replaces FFA, `g_gametype 0`  
chg : Changed default pmove_fixed value to 1. It doesn't need to be changed by cfg to work correctly.  
new : Created default .cfg files. Solves pmove_fixed not being used automatically, and some other configuration basics.  
```
```
new : Basic Linux automatic qvm compiling setup. Script at: src/qvm.sh  
... : Automated compilation from makefile  
... : Automated packing  
```
```md
# 0.0.0 (Mod Compiling Basics)  
new : Initial setup & compilation (manual)  
```
```md
# Worked by default  
: Surface flags (uses shader properties)  
: Vq3 movement (`pmove_fixed 1`)  
: Vq3 Weapons  
: Vq3 Teleports  
: vq3 Hurt Trigger  
: target_score  
: Map loading  
```

**Comment by heysokam** [comment]
Completed with 7d3e143
