### ISSUE TITLE
[milestone: 0.1.0] Minimal viable product

### ISSUE THREAD

**Issue by heysokam** [OpenQuake3/defrag#3]
> Note: Backport from the original markdown todo list

- [x] Full vq3 movement
- [x] Basic vq3 Weapons (should be full by default)  
- [x] Basic cpm strafing (Correct accel, aircontrol and A/D strafing)
- [x] Instant respawn
  (`g_combat.c/player_die()/line608` & others. switch timer to ms and make 1 mean immediate )
- [x] Gamemode "run"
- [x] Timer (local, best per session, all maps have TimeReset)
- [x] Gamemode "run" (basic)
  - [x] Definition in code (replaced FFA, g_gametype 0)
- [x] First cpm/vq3 alpha/dev release version

**Comment by heysokam** [comment]
Completed with 7d3e143
