### ISSUE TITLE
[milestone: 0.2.99] Patchnotes port from osdf-gpl + osdf-sdk

### ISSUE THREAD

**Issue by heysokam** [OpenQuake3/defrag#49]
### Patchnotes
```md
# v0.31a
## 2022.09.04
chg : Changed versioning system from `0.0.0x` to `0.00x` (start with 0.31a)
chg : Changed default player model from `sarge` to `ranger/pm`
chg : TEMP: All trigger_multiple entities are switched to 0.5 automatically. FIXME: This behavior should be to reset the entity state for player individually instead. Temp Hack until client-based entities are implemented.
chg : Disabled self dead messages in cg_event.c . Code is unchanged, only commented out the printf call
new : Skim Timer Hud element. Represents the value of pm_time, but skimming is its primary usage
... : Cvars for skim timer positioning: cg_timerSkim_x  cg_timerSkim_y
new : Cvars for run timer positioning: cg_timerActive_x  cg_timerActive_y  cg_timerBest_x  cg_timerBest_y
new : Cvars for speedmeter positioning: cg_speed_x  cg_speed_y
new : target_startTimer entity support  
new : target_stopTimer entity support  
new : Local Timer. Best per session. All maps have TimeReset (temporary hack until better Timer support)  
fix : .clang-format file no longer breaks the formatting of the Cvar lists in g_main.c and cg_main.c
chg : g_forcerespawn now means miliseconds, instead of seconds  
... : g_forcerespawn default value changed to 1. Previous behavior is now `g_forcerespawn 20000`  
new : Gamemode "run" (basic). Replaces FFA, `g_gametype 0`  
... : Replaced all GT_FFA enum entries with GT_RUN (value stays the same)
... : Replaced all "Free for All" text strings with "Defrag Run"
chg : Removed the "Waiting for players" message when cg.warmup is < 0
chg : Respawn minimum delay changed from 1700 to 0 on player_die()
chg : Powerups no longer drop on player_die()
chg : Score is now set to 0 on player_die(). For fragfilters
chg : Player persistant score is set to 0 on ClientSpawn(). For fragfilters
new : New function SetScore() on g_combat.c. Modified version of AddScore()
chg : (CPM) Rocket Launcher: Missile speed increased from 900 to 1000  
fix : (CPM) Rocket Launcher: Vertical self knockback scaling reduced to 1  
chg : (CPM) Rocket Launcher: Self knockback increased to 1.2  
```

```md
# 0.3.0
## 2022.07.14  
new : (CQ3) New physics: VQ3 aircontrol, with CPM tech (dj/ramps/slick/etc)  

## 2022.07.12  
fix : (VQ3) Fixed upramps giving the wrong amount of velocity on jump  
```
```md
# v0.3.0-r0
## 2022.07.18
new : Initial accel hud code has been added to the buildsystem. Currently inactive (WIP)  

## 2022.07.15
new : (VJK) New Mechanic: Jump Holdboost  
   ::  While holding jump, and moving at +375ups, you get extra jumpvel on each jump (375 is 1.5x of 250basespeed)  
   ::  It will reach the same heigh than vq3 in 8jumps, but will keep growing  
   ::  Starts at 225 base jumpvel, and increases by 5u each jump  
   ::  5u is 12% of 45. Which is the difference between vq3 and vjk jumpvel (270-225)  
new : (VJK) HoldBoost hud element  

## 2022.07.14
new : Sound event control system in cg_event.c  Can be used to stop any type of sound spam (autojump, rampslides, etc)  
new : (CQ3) New physics: VQ3 aircontrol, with CPM tech (dj/ramps/slick/etc)  

## 2022.07.13
new : pm_time hud element   (mainly related to skimming, but general purpose)  
new : New mechanic: Rampslides from Q2  (currently active for VQ4 physics)  
chg : (VQ1) Added Q3 Overbounces  
fix : (VQ1) Fixed visual glitch on physics change without `/map` command  
fix : (VQ1) Fixed downramps sometimes not giving a speed boost
new : (VQ1) New mechanic: Feetraise
... :       Crouching mid-air raises your feet by 14u (sbj). Allows jump to reach higher and further.  
new : (VQ4) Crouching mid-air raises your feet by 12u (sbj). Allows jump to reach higher and further.  

## 2022.07.12
fix : (VQ3) Fixed upramps giving the wrong amount of velocity on jump  
chg : (VJK) Reverted jumpvel back to 225 (in preparation for a new jump height mechanic)  
new : (VQ4) New physics : Quake 4 Inspired.  Activate with `/exec phy_vq4`  
   ::       Will have crouchsliding, rampslides (from q2/q4) and vq3 aircontrol  
new : (VQ4) Set groundaccel to 15 (same as original Q4 and cpm)  
new : (VQ4) New mechanic: Crouchslide  
   ::       Earns 2x frames of crouchslide per 1x frame spent in the air, capped at 2000ms   
   ::       Has 0 friction, and a separate accel value of 20  (could change after testing)  
```

### Pending osdf-sdk todo from `baseq3a`
```md
# Port from osdf-gpl to osdf-sdk (0.2.5)
- [x] Ported physics to baseq3a: CPM, VQ3 and CQ3
- [ ] CPM specific weapon/items changes
  - [ ] Rocket Launcher speed increased from 900 to 1000
  - [ ] Rocket Launcher knockback increased from 1 to 1.2
  - [ ] Item pickup size increased (from 36 to 66)
- [ ] Instant respawn (g_combat.c/player_die()/line608  & some other spots to switch timer to ms and make 1 mean immediate )
- [ ] Gamemode "run" (basic)
  - [ ] Definition in code (replaced FFA, g_gametype 0)
- [ ] Timer (local, best per session, all maps have TimeReset)
```

```md
# DONE : gpl to sdk
fix : .clang-format file no longer breaks function indentation in between macros

new : Test Makefile buildsystem for native windows compilation  
chg : Moved `build/linux/` folder to `build/make/` to reflect its multiplatform nature

new : Automated version management from the files `build/linux/build.py` and `code/game/mod-info.h`
```
```md
# Unreleased
## 2022.08.04
fix : Fixed a buildsystem bug. After changing to SCons nodes, the engine wasn't being built
```

**Comment by heysokam** [comment]
Completed with 7d3e143
